version: '3.7'

networks:
  visio_net:
    driver: bridge
 
volumes:
  grafana_vol: {}
  prometheus_vol: {}

services:
  app:
    image: harbor.sflabs.com.br/processo/petshop:latest
    container_name: petshop
    networks:
      - visio_net
    ports:
      - 3000:3000
    restart: on-failure
    
  grafana:
    image: grafana/grafana:9.3.1
    container_name: grafana
    networks:
      - visio_net
    volumes:
      - grafana_vol:/var/lib/grafana
    ports:
     - 4000:3000
    restart: on-failure

  prometheus:
    image: bitnami/prometheus:latest
    container_name: prometheus
    volumes:
    #  - ./prometheus/:/etc/prometheus/
     - prometheus_vol:/prometheus
    networks:
     - visio_net
    ports:
     - 9090:9090
    restart: on-failure

  node-exporter:
    image: bitnami/node-exporter:latest
    container_name: nodeexporter
    ports:
     - 9100:9100
    networks:
      - visio_net
    restart: on-failure
    