global:
  scrape_interval:     15s 
  scrape_timeout: 10s
      

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
         - targets: ['localhost:9090']
         - targets: ['localhost:3000']
           labels:
             grupo: 'Prometheus'
    #metrics_path: /metrics


  
  - job_name: 'petshop'

    scrape_interval: 15s
    scrape_timeout: 1s
    scheme: http
    metrics_path: /metrics
    static_configs:
     - targets: ['localhost:3000']
       labels:
         grupo: 'webapi'
  
