global:
  scrape_interval: 20s
  scrape_timeout: 20s
      
  external_labels:
      monitor: 'Projeto-Visio'

scrape_configs:
  - job_name: 'Prometheus'
    static_configs:
         - targets: ['prometheus:9090']
           labels:
             grupo: 'Prometheus'
    metrics_path: /metrics


  
  - job_name: 'Petshop'
    scrape_interval: 30s
    scrape_timeout: 30s
    scheme: http
    metrics_path: /metrics
    static_configs:
     - targets: ['petshop:3000']
       labels:
#         grupo: 'webapi'

  - job_name: 'Node-exporter'
    scrape_interval: 30s
    scrape_timeout: 30s
    scheme: http
    metrics_path: /metrics
    static_configs:
     - targets: ['node-exporter:9100']
       labels:
#         grupo: 'webapi'

  - job_name: 'Grafana'
    scrape_interval: 30s
    scrape_timeout: 30s
    scheme: http
    metrics_path: /metrics
    static_configs:
     - targets: ['grafana:3000']
       labels:
#         grupo: 'webapi'


  
