- hosts: all
  sudo: True
  user: tormin1
  tasks:
    - name: "Atualiza pacotes"
      shell: sudo apt-get update
    - name: "Instala o docker"
      shell: sudo apt-get install ca-certificates curl gnupg lsb-release
      shell: mkdir -p /etc/apt/keyrings
      shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      shell: chmod a+r /etc/apt/keyrings/docker.gpg
      shell: apt-get update
      shell: apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
   